language: node_js
version: 1.0

node_js:
  - 'node'

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

jobs:
  include:
    - stage: build
      before_install: npm install -g typescript
      before_script: npm run build
      script: npm run test
    - stage: deploy
      before_install: npm install -g typescript
      script: npm run build
      after_success: npm pack
      before_deploy: echo "Deploy to npm $NPM_TOKEN"
      deploy:
#        - provider: releases
#          token: $GITHUB_TOKEN
#          file_glob: true
#          file: "{YOURLIB}-*.tgz"
#          cleanup: false
#          on:
#            tags: true
#            branch: /^v\d+\.\d+(\.\d+)?(-\S*)?$/
        edge: true
        provider: npm
        skip_cleanup: true
        email: "kalee.mark@gmail.com"
        api_key: $NPM_TOKEN
        on:
          tags: true
          branch: /^v\d+\.\d+(\.\d+)?(-\S*)?$/

stages:
  - name: build
    if: NOT (branch =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/)
  - name: deploy
    if: branch =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/