language: nodejs

node_js:
  - 'node'

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_install:
  - npm install -g typescript

before_script:
  - npm run build

script:
  - npm run test

after_success:
  - npm pack

deploy:
  - provider: releases
    if: branch =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "{YOURLIB}-*.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    if: branch =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    skip_cleanup: true
    email: "kalee.mark@gmail.com"
    api_key: $NPM_TOKEN
    on:
      tags: true
      branch: master