language: node_js

node_js:
  - 'node'

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

#before_install:
#  - npm install -g typescript
#
#before_script:
#  - npm run build
#
#script:
#  - npm run test
#
#after_success:
#  - npm pack
#
#deploy:
#  - provider: releases
#    api_key: $GITHUB_TOKEN
#    file_glob: true
#    file: "{YOURLIB}-*.tgz"
#    skip_cleanup: true
#    on:
#      tags: true
#      branch: /^v\d+\.\d+(\.\d+)?(-\S*)?$/
#  - provider: npm
#    skip_cleanup: true
#    email: "kalee.mark@gmail.com"
#    api_key: $NPM_TOKEN
#    on:
#      tags: true
#      branch: /^v\d+\.\d+(\.\d+)?(-\S*)?$/

jobs:
  include:
    - stage: build
      before_install: npm install -g typescript
      before_script: npm run build
      script: npm run test
    - stage: deploy
      before_install: npm install -g typescript
      before_script: npm run build
      script: npm run test
      after_success: npm pack
      deploy:
        - provider: releases
          token: $GITHUB_TOKEN
          file_glob: true
          file: "{YOURLIB}-*.tgz"
          cleanup: false
          on:
            tags: true
            branch: /^v\d+\.\d+(\.\d+)?(-\S*)?$/

stages:
  - name: build
    if: NOT (branch =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/)
  - name: deploy
    if: branch =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/